### ISSUE TITLE
Spelling of Horst Feistel's surname ;-)

### ISSUE THREAD

**Issue by mjuenema** [inmcm/Simon_Speck_Ciphers#1]
Sorry for being pedantic but it's Feistel and not Fiestal. 

Aside from that thanks heaps for creating a Python implementation of the Speck Cipher. I am currently playing with Sigfox transmissions and given the small size of the data payload of at most 12 bytes (i.e. 96 bits) Speck/Simon are the only ciphers that are feasible to use. In fact, I mainly raised this issue to say thank you 👍 

Markus

**Comment by inmcm** [comment]
You're very welcome. Always nice to see code get discovered and used.
