### ISSUE TITLE
Fix for Simon CBC decrypt()

### ISSUE THREAD

**Issue by tebrost** [inmcm/Simon_Speck_Ciphers#2]
The implementation of Simon CBC decrypt() appears to be incorrect. It currently is:

        elif self.mode == 'CBC':
            a, b = self.decrypt_function(a, b)
            b ^= self.iv_upper
            a ^= self.iv_lower
            
            self.iv_upper = b
            self.iv_lower = a
            self.iv = (b << self.word_size) + a

The changes below allow the decrypt() to successfully decrypt data encrypted by the corresponding encrypt():

        elif self.mode == 'CBC':
            f, e = b, a
            a, b = self.decrypt_function(a, b)
            b ^= self.iv_upper
            a ^= self.iv_lower

            self.iv_upper = f
            self.iv_lower = e
            self.iv = (f << self.word_size) + e

**Comment by inmcm** [comment]
Thanks for pointing that out...Fixed!

**Comment by danijimmy19** [comment]
Is it possible for you to provide one example of how to use 'CTR', 'CBC', 'PCBC', 'CFB', 'OFB' modes for both encryption and decryption?

I appreciate your help.

**Comment by tebrost** [comment]
@danijimmy19 here you go. The odd thing about this simon interface is that it encrypts/decrypts integers instead of the usual byte arrays. So there is some conversion between the two. You can see that the ciphertext differs based on the mode used.
Good luck. 

```python
from simon import SimonCipher as simon

def int2bar(i, n): # convert int i to array of n bytes, little endian first
    return bytes([i>>(j<<3) & 0xff for j in range(0,n)])

def bar2int(bar): # convert byte array to int
    return sum([b << (j<<3) for j,b in enumerate(bar)])

key=0x112233445566778899aabbccddeeff00

msg=b"Is it possible for you to provide one example of how to use 'CTR', 'CBC', 'PCBC', 'CFB', 'OFB' modes for both encryption and decryption?"

for mode in [ 'CTR', 'CBC', 'PCBC', 'CFB', 'OFB' ]:
    print('-- Mode', mode, '--')
    E = simon(key, mode=mode).encrypt
    D = simon(key, mode=mode).decrypt
    for i in range(0,len(msg),16):
        pt = msg[i:i+16]
        ct = E(bar2int(pt))
        pt2 = int2bar(D(ct), 16)
        print(' Plaintext in:', pt)
        print('   Ciphertext:', hex(ct))
        print('Plaintext out:', pt2)
```

**Comment by tebrost** [comment]
@danijimmy19 here you go. The odd thing about this simon interface is that it encrypts/decrypts integers instead of the usual byte arrays. So there is some conversion between the two. You can see that the ciphertext differs based on the mode used.
Good luck.


```python
from simon import SimonCipher as simon

def int2bar(i, n): # convert int i to array of n bytes, little endian first
    return bytes([i>>(j<<3) & 0xff for j in range(0,n)])

def bar2int(bar): # convert byte array to int
    return sum([b << (j<<3) for j,b in enumerate(bar)])

key=0x112233445566778899aabbccddeeff00

msg=b"Is it possible for you to provide one example of how to use 'CTR', 'CBC', 'PCBC', 'CFB', 'OFB' modes for both encryption and decryption?"

for mode in [ 'CTR', 'CBC', 'PCBC', 'CFB', 'OFB' ]:
    print('-- Mode', mode, '--')
    E = simon(key, mode=mode).encrypt
    D = simon(key, mode=mode).decrypt
    for i in range(0,len(msg),16):
        pt = msg[i:i+16]
        ct = E(bar2int(pt))
        pt2 = int2bar(D(ct), 16)
        print(' Plaintext in:', pt)
        print(' Ciphertext:', hex(ct))
        print('Plaintext out:', pt2)
```
