### ISSUE TITLE
unsupported operand type(s) for >>: 'str' and 'int'

### ISSUE THREAD

**Issue by muraylen** [inmcm/Simon_Speck_Ciphers#4]
Hi, am trying to use your Simon and Speck ciphers in my project, however i keep getting the error "TypeError: unsupported operand type(s) for >>: 'str' and 'int' " on line 127 of either cipher. How do i go about that.

PS: My project is about sending encrypted traffic with Modbus-TCP

**Comment by inmcm** [comment]
Please refer to https://github.com/inmcm/Simon_Speck_Ciphers/tree/master/Python/simonspeckciphers#data-types
All inputs must be of type `int`. If you have str you need to encrypt you can easily convert them:
```python
>>> input_string = "This is 128 bits"
>>> input_int = int.from_bytes(input_string.encode(), 'big')
>>> hex(input_int)
'0x54686973206973203132382062697473'
```

**Comment by muraylen** [comment]
Hi, sorry to bother you but how can do i convert deciphered int values generated by **msg_int = sum([ord(c) << (8 * x) for x, c in enumerate(reversed(msg))])** back into string in python 2.7. Am using you example on [https://github.com/inmcm/Simon_Speck_Ciphers/tree/master/Python/simonspeckciphers#data-types] but stuck on converting the int values back to str
